<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Clabber.Backend.Application\Clabber.Backend.Application.csproj" />
    <ProjectReference Include="..\Clabber.Backend.Infrastructure\Clabber.Backend.Infrastructure.csproj" />
  </ItemGroup>

</Project>
